global:
  scrape_interval: 5s  # How often to scrape targets
  evaluation_interval: 5s  # How often to evaluate rules

scrape_configs:
  - job_name: "rabbitmq_consumer"
    static_configs:
      - targets: ["host.docker.internal:8080"]  # Change if running on a different system
